### ISSUE TITLE
Relatives href / src

### ISSUE THREAD

**Issue by CarusoX** [fernandochaza/marvel-landing#2]
To serve local files, it's better to use relative paths (don't start with the /).

When you load a webpage, the root is in the directory where the html code is.

Thanks to this, you can write the source of an image using `<img src="images/baby-groot-rm-background-rounded.webp" alt="">` (with no / at the front).

Using absolute paths may bring problems when deploying your site or working with others, since it assumes that you have the same folder structure outside the project itself.

**Comment by fernandochaza** [comment]
Solved! thanks for the clarification
